---
blank_issues_enabled: false
contact_links:
  - name: Kakarot Community Support
    url: https://github.com/sayajin-labs/kakarot-ssj/discussions
    about: Please ask and answer questions here.
