name: CI

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: kakarot-ssj-build

  tests-unit:
    uses: ./.github/workflows/tests-unit.yml
    with:
      run-fmt-check: false

  ef-tests:
    uses: ./.github/workflows/ef-tests.yml
    needs: [build]
    with:
      artifact-name: kakarot-ssj-build

  resources:
    runs-on: ubuntu-latest
    needs: [ef-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.14
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.14

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - run: poetry config installer.modern-installation false

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: make setup

      - name: Load performance artifacts
        uses: actions/download-artifact@v3
        with:
          path: resources
          name: resources

      - name: Check resources evolution
        run: |
          result=$(GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make check-resources 2>&1)
          echo "$result" >> "$GITHUB_STEP_SUMMARY"
