name: Generate and Upload Gas Snapshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "0.7.0"

      - name: Generate gas snapshot
        run: python scripts/gen_snapshot.py

      - name: Upload gas snapshot to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gas-snapshot
          path: gas_snapshot.json
