name: CI

permissions: read-all

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    # trunk-ignore(actionlint/runner-label)
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.0
      - run: scarb fmt --check
      - run: scarb build
      - run: scarb test
