name: CI

permissions: read-all

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/common.yml#build

  tests:
    # trunk-ignore(actionlint/runner-label)
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb test

  ef-tests:
    uses: ./.github/workflows/common.yml#ef-tests
